chore: Release a new strings version 0.2.0
objectionary/home pull request #114
Opened 2023-03-01 15:40 UTC by volodya-lombrozo

Release a new [strings](https://github.com/objectionary/eo-strings) version 0.2.0

2023-03-01 15:41 UTC, volodya-lombrozo commented
@Graur Could you have a look, please?

2023-03-01 15:44 UTC, Graur requested changes

2023-03-01 15:44 UTC, Graur commented on objects/org/eolang/txt/text.eo
> +  # @todo #107:30min Current implementation of trimmed method catches stackoverflow
@volodya-lombrozo You forgot to remove todo here

2023-03-01 15:44 UTC, Graur commented on objects/org/eolang/txt/text.eo
> +  # @todo #22:30min Current implementation using Java.
@volodya-lombrozo Same here

2023-03-02 07:34 UTC, volodya-lombrozo commented
@Graur Thank you. I've updated the PR and removed all todos. Could you take a look, again, please?

2023-03-02 08:19 UTC, Graur commented
@volodya-lombrozo `make` check is pending. Maybe we can increase stack size [here](https://github.com/objectionary/home/blob/master/make/jvm/pom.xml) ? And check again

2023-03-02 13:17 UTC, volodya-lombrozo commented
@Graur I've increased the stack-size, but seems that it didn't help.

2023-03-02 13:20 UTC, Graur commented
@volodya-lombrozo What about your local environment? Did `make` script also fail?

2023-03-02 14:41 UTC, Graur commented
@volodya-lombrozo Only this one is broken? Maybe we can disable it with `nop` object

2023-03-03 12:00 UTC, volodya-lombrozo commented
@Graur I've tried to ignore ~2 tests and the problem remains. I believe it has to be solved somewhere either in other PR or in `eo-strings` repository. What do you think is the best way to fix it?

2023-03-09 10:58 UTC, volodya-lombrozo commented
Was released here #116

2023-03-09 10:58 UTC, closed without merging